name: Stage 2 - Provision Staging & Deploy (No-Logs ARM)

on:
  workflow_run:
    workflows: ["CI - Test, Build & Push to ACR (Stage 1)"]
    types: [completed]

permissions:
  contents: read
  id-token: write

env:
  LOCATION: australiaeast
  # fixed RG you already granted Contributor on:
  STAGING_RG: sit722-staging-fixed
  ACR_NAME: ${{ secrets.ACR_NAME }}
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}

concurrency:
  group: stage2-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy-staging:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'testing' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install Azure CLI extensions
        run: |
          set -e
          az extension add --name containerapp --upgrade -y || true

      - name: Compute variables
        id: vars
        run: |
          echo "IMAGE_TAG=${{ github.event.workflow_run.head_sha }}" >> "$GITHUB_OUTPUT"
          echo "ENV_NAME=aca-${{ github.run_id }}"                   >> "$GITHUB_OUTPUT"

      - name: Ensure resource group exists
        run: az group create -n "${{ env.STAGING_RG }}" -l "${{ env.LOCATION }}"

      # ---- CREATE CONTAINER APPS ENV VIA ARM (NO LOGS) ----
      - name: Create Container Apps Environment (no logs, ARM)
        run: |
          set -e
          SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          RG="${{ env.STAGING_RG }}"
          ENV_NAME="${{ steps.vars.outputs.ENV_NAME }}"
          LOCATION="${{ env.LOCATION }}"
          API="2023-05-01"

          # idempotent PUT to create/update env with logs disabled
          az rest \
            --method PUT \
            --url "https://management.azure.com/subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RG}/providers/Microsoft.App/managedEnvironments/${ENV_NAME}?api-version=${API}" \
            --body "{
              \"location\": \"${LOCATION}\",
              \"properties\": {
                \"appLogsConfiguration\": { \"destination\": \"none\" }
              }
            }" \
            --output none

          # small wait until ready state to avoid races
          az containerapp env show -g "$RG" -n "$ENV_NAME" --query "provisioningState" -o tsv

      # ---- PULL CREDS FOR ACR (username/password) ----
      # Works with ACR Admin enabled OR fallback to repo secrets ACR_USERNAME/ACR_PASSWORD
      - name: Resolve ACR credentials
        id: acr
        run: |
          set -e
          USERNAME=""
          PASSWORD=""
          if az acr show -n "${{ env.ACR_NAME }}" >/dev/null 2>&1; then
            USERNAME=$(az acr credential show -n "${{ env.ACR_NAME }}" --query "username" -o tsv || true)
            PASSWORD=$(az acr credential show -n "${{ env.ACR_NAME }}" --query "passwords[0].value" -o tsv || true)
          fi
          if [ -z "$USERNAME" ] || [ -z "$PASSWORD" ]; then
            USERNAME="${{ secrets.ACR_USERNAME }}"
            PASSWORD="${{ secrets.ACR_PASSWORD }}"
          fi
          if [ -z "$USERNAME" ] || [ -z "$PASSWORD" ]; then
            echo "ACR credentials not available. Either enable Admin user on your ACR or set ACR_USERNAME and ACR_PASSWORD repo secrets."
            exit 1
          fi
          echo "username=$USERNAME" >> "$GITHUB_OUTPUT"
          echo "password=$PASSWORD" >> "$GITHUB_OUTPUT"

      # ---- DEPLOY APPS ----
      - name: Deploy/Update services (Container Apps)
        id: deploy
        run: |
          set -e
          RG="${{ env.STAGING_RG }}"
          ENV_NAME="${{ steps.vars.outputs.ENV_NAME }}"
          IMAGE_TAG="${{ steps.vars.outputs.IMAGE_TAG }}"
          REG_SERVER="${{ env.ACR_LOGIN_SERVER }}"
          REG_USER="${{ steps.acr.outputs.username }}"
          REG_PASS="${{ steps.acr.outputs.password }}"

          upsert_app () {
            local NAME=$1
            local PORT=$2
            local IMAGE=$3
            local EXTRA_ARGS=${4:-}
            if az containerapp show -g "$RG" -n "$NAME" >/dev/null 2>&1; then
              az containerapp update -g "$RG" -n "$NAME" \
                --image "$IMAGE" \
                --registry-server "$REG_SERVER" \
                --registry-username "$REG_USER" \
                --registry-password "$REG_PASS" \
                $EXTRA_ARGS
            else
              az containerapp create -g "$RG" -n "$NAME" \
                --environment "$ENV_NAME" \
                --image "$IMAGE" \
                --ingress external --target-port "$PORT" --transport auto \
                --registry-server "$REG_SERVER" \
                --registry-username "$REG_USER" \
                --registry-password "$REG_PASS" \
                $EXTRA_ARGS
            fi
          }

          upsert_app "customer-service" 8002 "${REG_SERVER}/customer-service:${IMAGE_TAG}"
          CUSTOMER_FQDN=$(az containerapp show -g "$RG" -n customer-service --query "properties.configuration.ingress.fqdn" -o tsv)

          upsert_app "product-service"  8003 "${REG_SERVER}/product-service:${IMAGE_TAG}"
          PRODUCT_FQDN=$(az containerapp show -g "$RG" -n product-service --query "properties.configuration.ingress.fqdn" -o tsv)

          upsert_app "order-service"    8001 "${REG_SERVER}/order-service:${IMAGE_TAG}" "--env-vars CUSTOMER_SERVICE_URL=http://${CUSTOMER_FQDN}"
          ORDER_FQDN=$(az containerapp show -g "$RG" -n order-service --query "properties.configuration.ingress.fqdn" -o tsv)

          upsert_app "frontend"            80 "${REG_SERVER}/frontend:${IMAGE_TAG}"
          FRONTEND_FQDN=$(az containerapp show -g "$RG" -n frontend --query "properties.configuration.ingress.fqdn" -o tsv)

          echo "CUSTOMER_URL=http://${CUSTOMER_FQDN}"  >> "$GITHUB_OUTPUT"
          echo "PRODUCT_URL=http://${PRODUCT_FQDN}"    >> "$GITHUB_OUTPUT"
          echo "ORDER_URL=http://${ORDER_FQDN}"        >> "$GITHUB_OUTPUT"
          echo "FRONTEND_URL=http://${FRONTEND_FQDN}"  >> "$GITHUB_OUTPUT"

      - name: Smoke test (light)
        run: |
          set -e
          echo "Waiting for apps to warm up..."
          sleep 30
          curl -fsS "${{ steps.deploy.outputs.FRONTEND_URL }}" >/dev/null
          curl -fsS "${{ steps.deploy.outputs.CUSTOMER_URL }}/health" || true
          curl -fsS "${{ steps.deploy.outputs.PRODUCT_URL }}/health"  || true
          curl -fsS "${{ steps.deploy.outputs.ORDER_URL }}/health"    || true

      - name: Print URLs
        run: |
          echo "FRONTEND: ${{ steps.deploy.outputs.FRONTEND_URL }}"
          echo "CUSTOMER: ${{ steps.deploy.outputs.CUSTOMER_URL }}"
          echo "PRODUCT : ${{ steps.deploy.outputs.PRODUCT_URL }}"
          echo "ORDER   : ${{ steps.deploy.outputs.ORDER_URL }}"
