name: Stage 2 - Destroy Staging

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: "Resource group to delete (e.g., sit722-staging-<run_id>)"
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Delete RG
        run: |
          az group delete -n "${{ inputs.resource_group }}" --yes --no-wait
          echo "Requested deletion of RG: ${{ inputs.resource_group }}"
